#!/bin/bash

dir="$1"

if [[ -z "$dir" ]]; then
    echo "Uso: $0 <directorio>"
    exit 1
fi

n=1
for file in "$dir"/*; do
    # saltar directorios y el .wallpaper
    [[ -f "$file" ]] || continue
    [[ "$(basename "$file")" == ".wallpaper" ]] && continue

    ext="${file##*.}"
    mv -v -- "$file" "$dir/  $n.$ext"
    ((n++))
done
